### ISSUE TITLE
export plotly objects as vectorial elements 

### ISSUE THREAD

**Issue by lucius81** [federicomarini/GeneTonic#40]
Hi Federico, i am already enjoying the GeneTonic. 

I would like to know if theres is a proper way to export the plotly objects, such as gs_radar graph, as a vectorial image (.svg or .pdf).

Kind regards,
Luciano

**Comment by federicomarini** [comment]
Hi Luciano,
Great to hear you are enjoying the software!
Basically, it seems that this needs to be done "directly via plotly": https://plotly.com/r/static-image-export/
The problem is that the orca approach seems deprecated, and the alternative way via `kaleido` requires some extra burden in the installation that I don't know if it is worth to put on every user...

Check in the R console

```
library(plotly)
?kaleido
```

So, in summary: if you use the functions in your standalone installation of R where you also happen to have it all set up for the usage via kaleido, you can just create the objects and export them as specified in the manpage.

HTH,
Federico

**Comment by lucius81** [comment]
Hi Federico, thanks a lot for your answer. I was able to solve the issue by adding these lines to my libraries configuration:

library(reticulate) 
reticulate::py_run_string("import sys") 

The second line seems to solve some issue with my python installation that was interfering with kaleido. After doing so i was able to use the command to export the plotly objects:
save_image (p, "export_file.pdf")

**Comment by federicomarini** [comment]
Glad the pointers helped!
